# Generated by Django 4.1.4 on 2022-12-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homeapp", "0002_alter_product_file_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="file_path",
        ),
    ]
